### ISSUE TITLE
zsh PS1 (prompt) comes out incorrectly

### ISSUE THREAD

**Issue by swoisz** [JPHutchins/envr#18]
Using zsh in Debian 12, the PS1 comes out incorrectly.

```sh
➜  smpmgr git:(main) . ./envr.ps1
\033[0;36m(smpmgr) ➜  smpmgr git:(main)
```

The escape sequences for color are not accepted. Perhaps zsh style color codes are needed instead of the bash ones?
Also, I am using oh-my-zsh which may cause issues? Haven't tried to repro on a machine without this.

some ideas I looked into a while back:
https://stackoverflow.com/questions/62953003/using-custom-colors-in-zsh-ps1-prompt-env-var-causes-problems-with-whitespace
https://dev.to/terngr/customize-prompt-in-zsh-prompt-in-z-shell-1528

**Comment by JPHutchins** [comment]
Can reproduce in Ubuntu!  

```
jp@LAPTOP-7UBN87U7:~/repos/smpclient$ zsh
LAPTOP-7UBN87U7% . ./envr.ps1
\033[0;36m(smpclient) LAPTOP-7UBN87U7%
```

**Comment by JPHutchins** [comment]
Here's a patch, see if this change fixes it at your convenience:

```patch
diff --git a/envr.ps1 b/envr.ps1
index 8d0b910..5098ada 100644
--- a/envr.ps1
+++ b/envr.ps1
@@ -270,7 +270,7 @@ _envr_set_prompt_prefix () {
         if [[ -n "${BASH:-}" ]] ; then
             PS1="\[\033[0;36m\](${_PROMPT}) ${PS1:-}"
         elif [[ -n "${ZSH_VERSION:-}" ]] ; then
-            PS1="\033[0;36m(${_PROMPT}) ${PS1:-}"
+            PS1="%F{36}(${_PROMPT})%F{reset} ${PS1:-}"
```

**Comment by swoisz** [comment]
![image](https://github.com/JPHutchins/envr/assets/157622666/1ab1991f-a17d-4cd3-b542-7b46f621a336)
Party on.
